[client]
showErrorDetails = true
toolbarMode = "minimal"
showSidebarNavigation = true
[server]
maxUploadSize=32
maxMessageSize =32
enableStaticServing = true
[theme]
primaryColor="#1D58EF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#16171f"
font="sans serif"
[ui]
hideTopBar = true



